version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes : 
      - type : bind 
        source : .
        target : /app
    ports:
      - "8020:8020"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - authnetwork
    command: uvicorn src.main:app --host 0.0.0.0 --port 8020
    container_name: ums_container

  postgres:
    image: postgres:latest
    ports:
      - "5441:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - authnetwork
    container_name: postgres_ums_container


networks:
  authnetwork:
    driver: bridge
    external: true

volumes:
  postgres_data:
  redis_config:
